version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: nginx
    ports:
      - "8080:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
